# Generated by Django 4.1 on 2022-11-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=30)),
                ('employee_name', models.CharField(max_length=30)),
                ('task_title', models.CharField(max_length=30)),
                ('task_end_date', models.CharField(max_length=30)),
            ],
        ),
    ]
