# Generated by Django 4.1 on 2022-11-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_employee_status_task_upload_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='upload_task',
            field=models.FileField(upload_to=''),
        ),
    ]
