# Generated by Django 4.1 on 2022-11-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_remove_task_taskid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='userid',
            field=models.IntegerField(default=True),
        ),
    ]
