# Generated by Django 4.1 on 2022-11-01 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_alter_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
