# Generated by Django 4.1 on 2022-11-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_alter_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='task_end_date',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='task_title',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='upload_task',
            field=models.FileField(default=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='task',
        ),
    ]
