# Generated by Django 4.1 on 2022-11-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_alter_employee_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='task_end_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='task_title',
        ),
    ]
