# Generated by Django 4.1 on 2022-11-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0023_employee_task_end_date_employee_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='task_end_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='task_title',
            field=models.CharField(max_length=30),
        ),
    ]
