# Generated by Django 4.1 on 2022-11-01 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0024_alter_employee_task_end_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='department',
        ),
    ]
