# Generated by Django 4.1 on 2022-11-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0025_delete_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='task_end_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='task_title',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='upload_task',
        ),
    ]
