# Generated by Django 4.1 on 2022-11-01 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0026_remove_employee_task_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_doj',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='update_on',
        ),
    ]
