# Generated by Django 4.1 on 2022-11-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0027_remove_employee_added_on_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee',
        ),
    ]
